### ISSUE TITLE
Finalize JSON5

### ISSUE THREAD

**Issue by seagreen** [json5/json5#136] opened 2016-12-08 21:19 UTC
The [EMCA JSON specification](https://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf) states, "Because it is so simple,  it is not expected that  the JSON grammar  will ever change."

Will this ever be a goal of JSON5?

I really like what I see of the project so far. It seems like a perfect solution to JSON being hard to write. However, looking through the issue list I see things like variables and datetimes being discussed which make me nervous. Not that those things are bad, they just don't fit with my use case of only needing "writeable JSON".

**Comment by aseemk** [comment] 2016-12-13 15:54
Great question! cc @jordanbtucker to chime in too.

I think that's a reasonable goal. The reality is that we _haven't_ shaken the boat with things like dates in all these years, so it's _probably_ unlikely that we will at this point either.

So there _could_ be some value in officially and formally "freezing" the spec... but I think there's also something to be said for learning from people's experiences and adapting to an ever-changing world.

How do others feel?

**Comment by seagreen** [comment] 2017-01-19 19:29
Hey @aseemk, a few thoughts:

(1) If you freeze JSON5 that doesn't mean in 5+ years from now the lessons from JSON5 can't be taken and developed into a new spec (JSON22?).

JavaScript will continue to change slowly, and someday it might be good to have another spec for easy to write JSON to keep up with it. But I actually think that process will go better in some ways if the specs are separate! Otherwise you end up in a very awkward period where a program may accept `.json5` documents, but you're not sure if you can use the new features or not.

Of course, this will end your ability to make small changes, which I admit is a real downside.

(2) If you think it's a good idea to move towards freezing JSON5 then it doesn't have to happen immediately. For instance, @jordanbtucker's issues are exactly the kind of thing that would be good to resolve first.

What do you think?

**Comment by aseemk** [comment] 2017-01-19 20:21
@seagreen: That sounds like a good perspective to me. Thanks! 👍

**Comment by seagreen** [comment] 2017-06-13 22:06
@aseemk: It's been half a year since I opened this issue. Do you think it's time to move towards finishing this thing? If so we should start making a list of blockers.

**Comment by seagreen** [comment] 2017-09-14 02:13
Bump. YAML is terrible, the world needs JSON5, to get adoption from serious users it has to actually be finished.

**Comment by techtonik** [comment] 2017-09-14 07:56
For me comments, trailing commas and non-quoted key names is a must. 

Multiline stings with quoted ends are not convenient for copy/paste - Python-like triple quoted strings are better, but they lack indentation for readability.

Everything else potentially makes parsing slower.

Considering that JSON is cross-language, this - `Infinity, -Infinity, NaN, and -NaN.` - is not portable.

**Comment by seagreen** [comment] 2017-09-14 18:08
@techtonik: Gotchya. I actually have no opinion on any of the specifics. I really like the general direction of JSON5, so I trust that whatever changes are made in the run up to finalization will be as classy as the rest of the spec.

The thing I do care about is that some kind of release does happen eventually. Even making a 1.x release and saying "nothing will change from this point except touchups" would go a long way, though of course I would prefer:

```
Because it is so simple, it is not expected that the JSON5 grammar will ever change.
```

**Comment by techtonik** [comment] 2017-09-14 20:18
Comments alone are worthy of release - https://stackoverflow.com/questions/tagged/json?sort=votes

**Comment by jordanbtucker** [comment] 2017-09-20 19:05
Please see the [v1.0.0 TODO list](https://github.com/json5/json5-spec/issues/1). If you are able to contribute to the spec, please do so on the [bikeshed](https://github.com/json5/json5-spec/tree/bikeshed) branch.

Beside completing the spec, I'm going to do a rewrite of the codebase because the current codebase is based on [Crockford's implementation](https://github.com/douglascrockford/JSON-js) whereas the new codebase will be based on the [ES5 implementation](https://es5.github.io/#x15.12.1).

**Comment by jordanbtucker** [comment] 2017-09-20 21:32
Please see the [v1.0.0 Milestone](https://github.com/json5/json5/milestone/1). Many of the issues/PRs will be fixed with the codebase rewrite, and I'll close those once I've merged that in, however, the CLI enhancements still need to be written along with their tests.

**Comment by jordanbtucker** [comment] 2017-09-25 08:17
**v1.0.0-beta** is live. Read the [CHANGELOG](https://github.com/json5/json5/blob/v1.0.0-beta/CHANGELOG.md) to see the new features and fixes.

Use it in your projects with:

```bash
npm install --save json5@beta
```

Use it in your terminal with:

```bash
npm install -g json5@beta
```

Use it in your browser with:

```html
<script src="https://unpkg.com/json5@beta/dist/index.js"></script>
```

**Comment by seagreen** [comment] 2017-09-25 14:56
@jordanbtucker: Awesome! That was blazingly fast. Thank you for all your work on it.

My only comment would be that I look forward to [this TODO](https://github.com/json5/json5-spec/blob/master/main.tex#L5) being filled out. I'm having trouble telling whether JSON5 is meant to be a superset of JSON or not. [This comment](https://github.com/json5/json5/issues/70#issuecomment-147766494) makes me think not, but the [ABNF](https://github.com/json5/json5-spec/blob/master/json5.abnf#L135) makes me think it is.

**Comment by aseemk** [comment] 2017-09-25 15:29
Amazing work @jordanbtucker!! :)

**Comment by jordanbtucker** [comment] 2017-09-25 16:38
@seagreen Thanks for the commendation. Here's the relevant section from the WIP spec regarding line and paragraph separators.

> **Paragraph and Line Separators**
> Like JSON, JSON5 allows the Unicode code points U+2028 and U+2029 to appear unescaped in strings. Since ECMAScript 5.1 does not allow these code points in strings, JSON5 authors should avoid including them in JSON5 documents. JSON5 parsers should produce a warning when they are found unescaped in strings. JSON5 generators should escape these code points in strings.

So officially, JSON5 is a strict superset of JSON and a loose subset of ES5 (but only loose regarding line and paragraph separators). I updated that [comment](https://github.com/json5/json5/issues/70#issuecomment-147766494) to reflect this now.

I haven't reviewed the ABNF with the new changes in mind, so I've added that to the [TODO list](https://github.com/json5/json5-spec/issues/1).

**Comment by jordanbtucker** [comment] 2017-09-25 17:34
I'm also curious to know what everyone things about the [`Date`](https://github.com/json5/json5/issues/3#issuecomment-331679238) and [`RegExp`](https://github.com/json5/json5/issues/91#issuecomment-331680535) support I've added in experimental branches.

**Comment by jordanbtucker** [comment] 2017-09-25 19:29
I forgot to document a new feature in the [CHANGELOG](https://github.com/json5/json5/blob/11316dc8eb8f8efd8c9bffe295a6063d5e2c2cce/CHANGELOG.md).

> New: `stringify` checks for a `toJSON5` method on objects and, if it exists, stringifies its return value instead of the object. `toJSON5` overrides `toJSON` if they both exist.

This is mainly useful in two cases:
- When you want to convert an object to `Infinity` or `NaN` before stringifying.
- When you want JSON5 output to differ from JSON output because reasons.

**Comment by jordanbtucker** [comment] 2017-09-28 08:58
The latest draft of the spec is up at https://json5.github.io/json5-spec/. Make sure you refresh the page to get the latest version. The date should be September 28, 2017.

I consider this the final version unless anyone finds anything wrong with it. Once finalized, it will say Standard instead of Draft, and the note about it being a draft will be removed.

I appreciate any feedback.

**Comment by aseemk** [comment] 2017-09-28 11:41
@jordanbtucker: This is excellent work!! Thank you as always. =)

Minor bug: "A JSON5 parser transforms a JSON text into another representation" should be "JSON5 text", right?

**Comment by jordanbtucker** [comment] 2017-09-28 17:02
@aseemk Good catch. I fixed that, added a JSON5Punctuator production that I missed, made it mobile friendly, and added a server script for development.

**Comment by jordanbtucker** [comment] 2017-09-30 05:56
I've made several changes to the spec. Many of the changes are only formatting or rewording, but there are a few important changes.

- Reworded the [introduction](https://github.com/json5/json5-spec/commit/33aee9941e56ed7a215cbc5c67498e54e6583aed) to state that JSON5 is a superset of JSON and removed the part about it being a subset of ES5 (https://github.com/json5/json5-spec/commit/3b5c1f1417b70f9c157cc1341a25b99114f6008d)
  - Related to that, JSON5 doesn't add new data types to ES5, but it does add new data types to JSON, namely `Infinity` and `NaN`, so I removed that part too.
- Fixed an error regarding what characters must be escaped in [strings](https://json5.github.io/json5-spec/#strings) (https://github.com/json5/json5-spec/commit/932a7d4a1e9cddda39e7215d1e8fdae9fec64d03)
- Reworded the parts about [Infinity and NaN](https://json5.github.io/json5-spec/#numbers) and added an example (https://github.com/json5/json5-spec/commit/9a6aa9cdf706fe8f4738220824f5e9285c84dba3)
- Refactored some [grammar](https://json5.github.io/json5-spec/#grammar) productions (https://github.com/json5/json5-spec/commit/f034fc028ff0cbcee444e915d497b798eab54275)
  - The diff is a little confusing, but essentially I added a _JSON5Identifier_, _JSON5Null_, and _JSON5Boolean_ production to the lexical grammar and ensured that the syntactic grammar only references the JSON5 lexical grammar and not the ES5 lexical grammar.
- Addressed octal [escapes](https://json5.github.io/json5-spec/#escapes) in strings (https://github.com/json5/json5-spec/commit/33aee9941e56ed7a215cbc5c67498e54e6583aed)

That last change also required a bug fix committed in c952a0d6e0f6fc285461c52cdd2d0f4952f6249c and 78b403a9ef60602741065907b032040dd9b780a5, which is live on npm at `json5@beta`.

**Comment by jordanbtucker** [comment] 2017-09-30 19:31
A while ago, I ran the beta against the v0.5.1 test cases to make sure there were no regressions and fixed the bugs I found. Now, I've run v0.5.1 against the beta test cases to see if there were any changes I forgot to document. I found a few and updated the [CHANGELOG](https://github.com/json5/json5/blob/beta/CHANGELOG.md). Here's a summary. (Subpoints are additional information not included in the CHANGELOG.)

- New: Unicode property names <ins>and Unicode escapes in property names</ins> are supported. (#1)
  - Example: `{ \u0061: true }` and `{ a: true }` are equivalent.
  - Character and escapes can be mixed, so `{ abc\u0064\u0065\u0066: true }` and `{ abcdef: true }` are equivalent.
  - The code points represented by the escaped character must still conform to _IdentifierName_, so the following will fail: `{ \u0000: true }`
- New: In addition to the white space characters space `\t`, `\v`, `\f`, `\n`, `\r`, and `\xA0`, the additional white space characters `\u2028`, `\u2029`, and all other characters in the Space Separator Unicode category are allowed.
- New: In addition to the character escapes `\'`, `\"`, `\\`, `\b`, `\f`, `\n`, `\r`, and `\t`, the additional character escapes `\v` and `\0`, hexadecimal escapes like `\x0F`, and unnecessary escapes like `\a` are allowed in string values and string property names.
- New: When a character is not allowed in a string, `stringify` outputs a character escape like `\t` when available, a hexadecimal escape like `\x0F` when the Unicode code point is less than 256, or a Unicode character escape like `\u01FF`, in that order.
  - Example: `'\u0061\u0009\u000F\u01FF'` becomes `'a\t\x0F\u01FF'`
- Fix: `stringify` properly handles the `key` argument of `toJSON(key)` methods. `toJSON5(key)` follows this pattern.
  - Raise your hand if you didn't know this was a [thing](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#toJSON()_behavior). :hand:
- Fix: `stringify` accepts `Number` and `String` objects as its `space` argument.
  - Related but different: #154
- Fix: In addition to a function, `stringify` also accepts an array of keys to include in the output as its `replacer` argument. Numbers, `Number` objects, and `String` objects will be converted to a string if they are given as array values.
  - Raise your other hand if you didn't know this was a [thing](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#Parameters) either. :hand:

**Comment by aseemk** [comment] 2017-09-30 19:48
Nice work! I raise both of my hands 🙌 — this is purposely a double-entendre. =)

**Comment by seagreen** [comment] 2017-10-01 02:21
@jordanbtucker: This is amazingly fast progress. Also, thanks for the clarification that JSON5 is definitely a superset of JSON!

My only concern is the clarity of this line:

> JSON5 generators should escape these code points in strings.

It depends a lot on the precise meaning of "should" here. If I write a program that consumes JSON5 created by a generator, can I rely on those code points being escaped (AKA that the JSON5 will not actually be a superset of JSON, but rather an overlapping set?) You may define how you're using "should" somewhere else in the spec, if so sorry I missed it!

**Comment by jordanbtucker** [comment] 2017-10-01 03:18
Good question. The use of the word "should" has the same meaning as in [RFC 2119](https://tools.ietf.org/html/rfc2119).

> **SHOULD**   This word, or the adjective "RECOMMENDED", mean that there may exist valid reasons in particular circumstances to ignore a particular item, but the full implications must be understood and carefully weighed before choosing a different course.

So, no you should not rely on this behavior, especially since the JSON spec does not recommend that generators escape those characters and JSON5 parsers must be backward compatible with JSON.

The old Bikeshed version of the spec referenced this RFC, but the Ecmarkup version doesn't. I'll be sure to add that reference back in.

**Comment by seagreen** [comment] 2017-10-01 04:53
@jordanbtucker: Excellent😄 You've fully addressed all my concerns.

**Comment by jordanbtucker** [comment] 2017-10-01 18:14
I just [updated](https://github.com/json5/json5-spec/compare/ac07e294ad9c43d9a0c4aa59decd115ec88af60d...6e81895c24d3b4d13510d1bf0f3fc663f2ad1bb1) the spec with a clause about the keywords and a few other fixes and clarifications.

**Comment by jordanbtucker** [comment] 2017-10-25 21:54
Apologies for the lack of updates lately. I've been busy with work and personal things. The reason I haven't released v1.0 yet is because I discovered a [bug](https://github.com/json5/json5/issues/159) in the reference implementation, and I think it's important to release a working reference implementation along with the spec.

I've already fixed the bug, so v1.0 of the spec and reference implementation should be ready to be released after the READMEs, and CHANGELOGs are updated.

After v1.0 is released, I will continue work on refactoring `parse` to use `Parser` and `Lexer` classes, which will facilitate the development of modules that must inspect JSON5 code, e.g. an ESLint parser.

**Comment by MartinMuzatko** [comment] 2017-11-09 15:58
Hello. Having no idea about the entire standardization process of the w3c and tc39 etc.. Is this issue the ticket for us, to make JSON5 an official supported standard?

**Comment by jordanbtucker** [comment] 2017-11-17 00:31
@MartinMuzatko At this point in time, there is no intention to make JSON5 a W3C or TC39 spec, and there isn't really a need to. The [Source Maps](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit#heading=h.djovrt4kdvga) spec is just a Google Doc, but it's in use by almost every modern transpilation software today, and I plan to implement it into JSON5 at some point too.

As long as everyone agrees with the official [JSON5 spec](https://json5.github.io/json5-spec/), it will be a standard regardless of whether it's endorsed by W3C or TC39.

**Comment by hax** [comment] 2017-12-19 09:02
@jordanbtucker Endorsement by TC39/W3C may be helpful to avoid many branches such as [JSON6](https://github.com/d3x0r/JSON6), JSON7, etc 😁

**Comment by jordanbtucker** [comment] 2018-03-11 21:59
v1.0.0 has landed.

**Closed by jordanbtucker** 2018-03-11 21:59 UTC
Labels: documentation :page_facing_up:

**Comment by aseemk** [comment] 2018-03-11 22:48
Fantastic work as always @jordanbtucker!! 😃
